### PR TITLE
feat(rules): add `short` parameter to `no-alias-methods`

### LINKED ISSUE #234: Add an option to `no-alias-methods` to prefer the alias methods.
I find the rule very useful, because the consistent naming allows better search and replacement.
However, the "canonical" names are almost twice as long.
I appreciate that there may be more references to the "canonical" names out in the wild, but I find the official documentation sufficient, and the aliases search well enough there.

### PR DESCRIPTION
**Pull request by qm3ster**
Fixes #234 

@macklinu please have a look if you think this should be improved

### CODE REVIEW

**Comment by qm3ster** [comment]
Yup, [only one build failed](https://travis-ci.org/jest-community/eslint-plugin-jest/builds/504182577), not my fault

**Comment by macklinu** [comment]
With this option added, I feel like the `no-alias-methods` rule name doesn't make sense anymore. Maybe something like `consistent-alias-methods`? That would be a breaking change, but I'm curious to think about the addition to this rule and what would be the best naming / clearest API for it and see if we'd want to introduce a breaking change for it or not.

Thoughts from others (maintainers and community)?

**Comment by qm3ster** [comment]
Thank you for your feedback.
Yeah, I just wanted to make it non-breaking. Felt like that would make it easiest to get it in right away.

I think the perfect API would be `alias-methods: "never"|"short"` (Doubt `"always"` is a good one here)
It would be easy to add it in a non-breaking fashion by duplicating the rule under the new name and in the current or future version marking the `no-` one deprecated.

I can envision someone wanting to just manually configure which names are used, but I'm sure that `"short"` would be the most popular strategy after `"canonical"`. Can always add `"custom"` variant for first positional argument to take more parameters.

**Comment by SimenB** [comment]
Sorry about the late response!

I'm down with the idea of a separate rule, marking the current one as deprecated in the docs, and removing it in the next major

**Comment by SimenB** [comment]
@qm3ster ping 🙂

**Comment by qm3ster** [comment]
Yes, it me!
I agree with that viewpoint.
I suppose this PR should be closed.
If I go ahead with that, it should be a new one.

**Comment by SimenB** [comment]
That works for me 🙂 Feel free to proceed however you like

**Pull request closed without merging**
