### PR TITLE
Drop Node 6 (and other Major changes)

### PR DESCRIPTION
**Pull request by G-Rath**
Superseeds #440

### CODE REVIEW

**Comment by G-Rath** [comment]
@SimenB I started looking to merge `no-disabled-tests` & `no-commented-out-tests`, but ended up settling on that I think that'd be detracting.

Having done some more thinking, I think it would make sense to have `no-disabled-tests` recommended as `error`, and `no-commented-out-tests` recommended as `warning (which is also why I don't think they should be merged: they can't be given different warning levels).

My thinking is that disabled tests are still executable code: Jest can see & interact w/ them on some level. Meanwhile, comments are something that by design Jest can't even see.

I've worked w/ a number of libraries that has used comments to keep something in version control to be enabled later (case and point: we have `// 'jest/no-mocks-import': 'error',` in the recommend rules).

A common example is for when you're got a test failing on a particular library or node version, that you're wanting to disable for the time being - having your CI break on that isn't helpful, and means you have to "hide" code in VCS.

As such I think erroring on comments will frustrate developers compared to a warning.

Let me know what you think 🙂

**Comment by SimenB** [comment]
> @SimenB I started looking to merge `no-disabled-tests` & `no-commented-out-tests`, but ended up settling on that I think that'd be detracting.

fair enough, makes sense 👍 

---

the body of 88a2921f0381e7100747b657e145816ce49038ce should how _how_ it's breaking as well, and a mini migration guide. E.g. "node 6 is EOL, minimum supported version is now 8" or something. dd4422394e91a6b57ce60156e04f47812eeb4b2c & 2cbf91bac1b14d4eb97a5639b60f9c74bb906735 should also have `BREAKING CHANGE` in the body - the changelog/release will list all breaking changes separately.

**Comment by G-Rath** [comment]
> fair enough, makes sense 👍

Sweet, I'll pop it in on warning.

> the body of 88a2921 should how how it's breaking as well, and a mini migration guide. E.g. "node 6 is EOL, minimum supported version is now 8"

That makes sense 😄 I'll update those commits in a bit.

> dd44223 & 2cbf91b should also have BREAKING CHANGE in the body

Huh I thought I did add it to them - oh well, I'll rebase those too.

-----

Aside from whats covered in previous comments, issues & open PRs, is there anything else you've been thinking of doing that would require a breaking change?

I'm happy to look into things, if you'd just like to chuck me a list of thoughts 🙂

**Comment by SimenB** [comment]
pushed update of all deps - I'll stay away so you can rebase now 👍 

>Aside from whats covered in previous comments, issues & open PRs, is there anything else you've been thinking of doing that would require a breaking change?

nope, I think stuff should be covered by open PRs and issues

**Comment by G-Rath** [comment]
> pushed update of all deps - I'll stay away so you can rebase now 👍

That was the fun part I was saving till last :'( 

jk cheers - I'll hopefully have this wrapped up by tomorrow :)

**Comment by SimenB** [comment]
add `closes #410` to 88a2921f0381e7100747b657e145816ce49038ce as well

**Comment by SimenB** [comment]
@G-Rath I've updated the commit bodies, so the only thing we need to is is figure out what rules we wanna move to recommended and I think we're good to go. I can open up a different PR for it so we can discuss there

**Comment by SimenB** [comment]
@G-Rath I think this is ready to go. any outstanding issues with breakage we wanna handle?

**Comment by G-Rath** [comment]
@SimenB `no-standalone-expect` - did we want that in `recommended`, since it should catch actual bugs?

If you're working on the branch right now, could you bump TypeScript to the latest version? I think it's good to have that as high as possible, since they don't follow semver quite the same way, and I'd rather just make sure everyone's explicitly on the highest possible version when deving.

I'd be keen to hit the merge button if that's alright w/ you, just for the buzz. I'll do a final look over the code base now to see if there was anything else I think could be worth doing in the major, but I think we're good.

**Comment by SimenB** [comment]
> @SimenB `no-standalone-expect` - did we want that in `recommended`, since it should catch actual bugs?

good call - I'll add it to the other commit and force push it right away

>If you're working on the branch right now, could you bump TypeScript to the latest version? 

`yarn outdated` is happy, so every dependency is on the latest version, and we explicitly depend on the latest version of `experimental-utils`, so I think we're covered here.

>I'd be keen to hit the merge button if that's alright w/ you, just for the buzz.

sure, just make sure to use rebase merging (still the big green button) rather than squash merge as we want the separate commits to land

**Comment by G-Rath** [comment]
I just realised we've got:

>     "@typescript-eslint/eslint-plugin": "^2.5.0",
>    "@typescript-eslint/parser": "^2.5.0",

So far it seems to be behaving itself, but just in case you didn't know, it's that version has been causing some weird problems in IDEs.

CI should be fine, but just wanted to mention it in case it starts playing up.

**Comment by SimenB** [comment]
I haven't had any issues personally at least. and they're pretty responsive on issues, so I think we're good (can tweak the version later if we want to)

feel free to merge this when you're ready 👍

**Comment by G-Rath** [comment]
> they're pretty responsive on issues

Oh for sure, and they're trying to get it fixed, but the problem is that it's a very hard one to reproduce -It's very much a heisenbug.

> feel free to merge this when you're ready 👍

I shall do so noooowwww!

**Comment by G-Rath** [comment]
@SimenB `valid-title` didn't make it into recommended 😱 

https://github.com/jest-community/eslint-plugin-jest/blob/master/src/index.ts

Did you rebase it away on purpose or by accident, and is there anything we can do aside from shrugging and going "bugger, oh well"?

**Comment by SimenB** [comment]
I didn't _purposefully_ remove it at least. no biggie though, I vote for 🤷‍♀

**Comment by G-Rath** [comment]
I think it's a pretty cool rule, but oh well.

I'll leave any action taking up to you, if you want to do anything, but yeah no biggie.

**Pull request merged**
