### PR TITLE
chore(index): move globals into json file

### PR DESCRIPTION
**Pull request by G-Rath**
I was happily surprised to find out that git can cherry-pick across file types :D

### CODE REVIEW

**Comment by SimenB** [comment]
@G-Rath this fails locally:

```sh-session
$ yarn build && node -p 'require("./")'
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './globals.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/simen/Development/eslint-plugin-jest/lib/index.js:7:39)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

I fixed it with b61ec87550b938da3eedb77a70b6aff7c86f2569 so this is just a heads up 🙂

**Comment by G-Rath** [comment]
Let me guess - b/c it doesn't get copied over. duh that was silly of me to miss 😬

**Comment by SimenB** [comment]
no worries, glad we caught it before release, tho

**Comment by G-Rath** [comment]
I've been bitten before by that iirc - it's kind of weird b/c yeah TS gladly imports those files, but [won't "build" them](https://stackoverflow.com/questions/42421392/is-it-possible-to-include-a-json-file-when-using-typescript-with-a-tsconfig-json) :/

**Pull request merged**
