### PR TITLE
Fixing a typo in the `require-to-throw-message` docs

### PR DESCRIPTION
**Pull request by erunion**

### CODE REVIEW

**Comment by G-Rath** [comment]
Probably should have been a `doc` commit, but nice to have a bug release w/ the chore stuff I did so 🤷‍♂ 

@SimenB `danger` seems to be having some troubles of late - can we get that fixed?

**Comment by erunion** [comment]
Ah sorry, I made the change directly in Github so commitlint didn't get run.

**Comment by G-Rath** [comment]
commitlint wouldn't have picked it up anyway :)

The fault technically is mine, as I can re-write the commits on merge via squash, but I'm glad to have the chore changes + updated lock file landed for stability purposes, so no big deal.

**Comment by SimenB** [comment]
>@SimenB `danger` seems to be having some troubles of late - can we get that fixed?

It should hopefully help once we don't have to build it - https://github.com/danger/danger-js/pull/938 & https://github.com/danger/swift/issues/292

**Pull request merged**
