### PR TITLE
feat: upgrade `@typescript-eslint/utils` to v6

### PR DESCRIPTION
**Pull request by SimenB**
There are so many breaking changes in v6 I don't think we'll be able to properly support v5 and v6 at the same time...

I started here and just ended up frustrated 😛 @G-Rath I dunno if you wanna give it a whack?

### CODE REVIEW

**Comment by G-Rath** [comment]
@SimenB just to check, do we _need_ to support both or move to v6 right now? I'm still triaging the new major and so far it looks like everything still works fine from a consumer POV but want to double check I've not missed something.

**Comment by SimenB** [comment]
I'd prefer to have CI verify it works with both, but there is no rush at all. It's totally fine to stay on the old version for now

**Comment by probablyup** [comment]
ooc if this linter plugin isn't updated to the new version and `@typescript-eslint/*@6` is used in a linting setup, will that cause problems with both versions being installed and potentially used simultaneously?

**Comment by SimenB** [comment]
You can use v6 of the plugin already

**Comment by probablyup** [comment]
> You can use v6 of the plugin already

Oh, what is this PR doing then?

**Comment by erunion** [comment]
Any updates on this? It's starting to cause some downstream issues with packages that depend on v6 of the parser.

```
> npm ci
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: eslint-plugin-typescript-sort-keys@3.0.0
npm ERR! Found: @typescript-eslint/parser@5.59.7
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   peer @typescript-eslint/parser@"^5.0.0" from @typescript-eslint/eslint-plugin@5.59.7
npm ERR!   node_modules/@typescript-eslint/eslint-plugin
npm ERR!     peerOptional @typescript-eslint/eslint-plugin@"^5.0.0 || ^6.0.0" from eslint-plugin-jest@[2](https://github.com/readmeio/readme/actions/runs/6028891616/job/16357165874?pr=9956#step:4:2)7.2.[3](https://github.com/readmeio/readme/actions/runs/6028891616/job/16357165874?pr=9956#step:4:3)
npm ERR!     node_modules/eslint-plugin-jest
npm ERR!       eslint-plugin-jest@"^27.2.3" from @readme/eslint-config@12.2.0
npm ERR!       node_modules/@readme/eslint-config
npm ERR!         dev @readme/eslint-config@"^12.2.0" from the root project
npm ERR!         2 more (@readme/react, @readme/schema-form)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @typescript-eslint/parser@"^6" from eslint-plugin-typescript-sort-keys@3.0.0
npm ERR! node_modules/eslint-plugin-typescript-sort-keys
npm ERR!   dev eslint-plugin-typescript-sort-keys@"^3.0.0" from the root project
npm ERR!   eslint-plugin-typescript-sort-keys@"^3.0.0" from @readme/eslint-config@12.2.0
npm ERR!   node_modules/@readme/eslint-config
npm ERR!     dev @readme/eslint-config@"^12.2.0" from the root project
npm ERR!     2 more (@readme/react, @readme/schema-form)
npm ERR! 
npm ERR! Conflicting peer dependency: @typescript-eslint/parser@6.5.0
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   peer @typescript-eslint/parser@"^6" from eslint-plugin-typescript-sort-keys@3.0.0
npm ERR!   node_modules/eslint-plugin-typescript-sort-keys
npm ERR!     dev eslint-plugin-typescript-sort-keys@"^3.0.0" from the root project
npm ERR!     eslint-plugin-typescript-sort-keys@"^3.0.0" from @readme/eslint-config@12.2.0
npm ERR!     node_modules/@readme/eslint-config
npm ERR!       dev @readme/eslint-config@"^12.2.0" from the root project
npm ERR!       2 more (@readme/react, @readme/schema-form)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/runner/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-08-30T18_5[4](https://github.com/readmeio/readme/actions/runs/6028891616/job/16357165874?pr=9956#step:4:5)_06_1[5](https://github.com/readmeio/readme/actions/runs/6028891616/job/16357165874?pr=9956#step:4:6)1Z-debug-0.log
```

We can solve this with a `npm ci --force` but that's less than ideal.

**Comment by G-Rath** [comment]
That's not because of `eslint-plugin-jest` - we are compatible with v6; my [works eslint config](https://github.com/ackama/eslint-config-ackama) is using it without issue along with on other projects internally.

**Pull request closed without merging**
