### PR TITLE
No jest import fixes

### PR DESCRIPTION
**Pull request by ranyitz**
Following to #98, This PR:

* Add `no-jest-import` rule to the `README.md`.
* Make it `recommended`.
* Set error level to `warn`.

### CODE REVIEW

**Comment by SimenB** [comment]
Technically it's a breaking change adding it to `recommended`, but if people _do_ import `jest` then it doesn't work, so it might be OK.

@thymikee thoughts?

**Comment by thymikee** [comment]
I'd rather say it's a fix, being breaking at the same time. I'm OK with adding it to the next minor/patch

**Comment by SimenB** [comment]
🤞

**Pull request merged**
