### PR TITLE
feat(no-unnecessary-functions): create rule

### PR DESCRIPTION
**Pull request by AndrewLeedham**
Creates a new rule called "no-unnecessary-functions", which prevents calls to `jest.resetModules`, `jest.clearAllMocks`, `jest.resetAllMocks` and `jest.restoreAllMocks`

fixes: #112

### CODE REVIEW

**Comment by G-Rath** [comment]
Thanks for the contribution!

I don't think this is worth shipping in `jest` as its own rule as-is, as you can do it easily with [`no-restricted-syntax`](https://eslint.org/docs/rules/no-restricted-syntax), i.e.:

```
{
  "selector": "CallExpression[callee.name='resetModules']",
  "message": "Do not use resetModules"
}
```

**Comment by AndrewLeedham** [comment]
> Thanks for the contribution!
> 
> 
> 
> I don't think this is worth shipping in `jest` as its own rule as-is, as you can do it easily with [`no-restricted-syntax`](https://eslint.org/docs/rules/no-restricted-syntax), i.e.:
> 
> 
> 
> ```
> 
> {
> 
>   "selector": "CallExpression[callee.name='resetModules']",
> 
>   "message": "Do not use resetModules"
> 
> }
> 
> ```

Fair point, perhaps it would be more use if it automatically detected which are unnecessary from the users jest config? Are there any other rules that use the jest config?

**Comment by G-Rath** [comment]
Sorry for the late reply. You've hit the nail on the head regarding the jest config -  we need to figure out a way to get the config that's stable, performant, and secure.

There's a few ways we could do it, but overall it's a hard challenge as the config can come from a number of places: from `package.json`, depending on paths, if it's javascript then it could import things, if its typescript it needs to be transpiled, etc

**Comment by AndrewLeedham** [comment]
Perhaps we could utilise https://github.com/facebook/jest/blob/master/packages/jest-config/src/index.ts#L33. Although I am not 100% sure how to determine which project relates to which file, perhaps there is another of Jest's packages that could help us there. Re-implementing that behaviour would likely be un-stable, so I would have thought improving what Jest exposes would be a more robust route if needs be.

**Comment by G-Rath** [comment]
Yeah, there's a lot of edge-cases to cover, which is why we've not done it yet - iirc there was talk about possibly calling the jest cli, but even that has edge cases 🤷

**Comment by SimenB** [comment]
Should definitely use `jestConfig.readConfig`. But there's (at least) 3 issues with that currently

1. It's async, so we cannot do it at all (`eslint@7` introduced some async APIs (when using it programatically see https://eslint.org/blog/2020/05/eslint-v7.0.0-released#new-eslint-class), but I don't think rules can use it)
1. As mentioned, figuring out which config (project) applies to which file is buried in Jest's source code and would need to be surfaced somehow from it (it's a combination of include and ignore patterns in non-obvious ways)
1. We'd need to get it once and cache it for the rest of the rules that might want it. Might work with a util that caches it locally though

**Comment by AndrewLeedham** [comment]
1. Would it be plausible to provide a `jestConfig.readConfig.sync` function for this purpose?
2. Is there a ticket open for this on Jest or does one need creating?
3. 👍

**Comment by SimenB** [comment]
>Would it be plausible to provide a `jestConfig.readConfig.sync` function for this purpose?

No, as we need to use `import()` to load ESM config, and that is asynchronous (by specification, as mentioned)

>Is there a ticket open for this on Jest or does one need creating?

Feel free to create one! Or send a PR 🙂 Note that due to 1 we are blocked, but having the APIs ready from Jest's side would be nice so we only need to wait for ESLint

**Comment by AndrewLeedham** [comment]
> No, as we need to use import() to load ESM config, and that is asynchronous (by specification, as mentioned)

Ah because a Jest config can be ESM. I see what you mean now 👍 

> Feel free to create one! Or send a PR 🙂 Note that due to 1 we are blocked, but having the APIs ready from Jest's side would be nice so we only need to wait for ESLint

I am not sure where this logic currently belongs, or really how it works, but I have raised an issue for now: https://github.com/facebook/jest/issues/11171

**Comment by G-Rath** [comment]
@AndrewLeedham are you ok if I close this to keep things tidy?

**Pull request closed without merging**
