### PR TITLE
fix:(valid-title): check if node has arguments first

### LINKED ISSUE #435: [valid-title]: TypeError when no arguments passed to test: Cannot read property 'type' of undefined
```
it();
```

```
TypeError: Cannot read property 'type' of undefined
Occurred while linting C:\Users\G-Rath\workspace\projects-personal\terraporter\test\src\printers\printPrimitiveLiteral.spec.ts:4
    at isStringLiteral (C:\Users\G-Rath\workspace\projects-personal\terraporter\node_modules\eslint-plugin-jest\lib\rules\utils.js:53:47)
    at isStringNode (C:\Users\G-Rath\workspace\projects-personal\terraporter\node_modules\eslint-plugin-jest\lib\rules\utils.js:85:43)
    at getNodeTitle (C:\Users\G-Rath\workspace\projects-personal\terraporter\node_modules\eslint-plugin-jest\lib\rules\valid-title.js:24:34)
    at CallExpression (C:\Users\G-Rath\workspace\projects-personal\terraporter\node_modules\eslint-plugin-jest\lib\rules\valid-title.js:48:23)
    at listeners.(anonymous function).forEach.listener (C:\Users\G-Rath\workspace\projects-personal\terraporter\node_modules\eslint\lib\linter\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Users\G-Rath\workspace\projects-personal\terraporter\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Users\G-Rath\workspace\projects-personal\terraporter\node_modules\eslint\lib\linter\node-event-generator.js:253:26)
    at NodeEventGenerator.applySelectors (C:\Users\G-Rath\workspace\projects-personal\terraporter\node_modules\eslint\lib\linter\node-event-generator.js:282:22)
    at NodeEventGenerator.enterNode (C:\Users\G-Rath\workspace\projects-personal\terraporter\node_modules\eslint\lib\linter\node-event-generator.js:296:14)
```

### PR DESCRIPTION
**Pull request by G-Rath**
Fixes #435

### CODE REVIEW

**Comment by G-Rath** [comment]
@SimenB Would be keen to release this - is triggering release bot something I can do, or does it require your private tokens?

**Comment by SimenB** [comment]
just restarting the ci build should work (I just did so)

**Comment by G-Rath** [comment]
Oh is releasing done for the master branch? Interesting, but cheers!

I'll explore the configs and see how it's all connected :)

**Comment by SimenB** [comment]
every build on master, yes

**Comment by SimenB** [comment]
should explore moving to gh actions 👍

**Comment by G-Rath** [comment]
> should explore moving to gh actions 👍

I'd be keen to get in on that action - We've been wanting to explore it at work, but not had an active project to explore it w/.

**Comment by SimenB** [comment]
> I'd be keen to get in on that action

hah 😆

**Pull request merged**
