### PR TITLE
chore: add codecov integration

### LINKED ISSUE #69: Considering adding codecov integration
What do you say about adding [codecov](https://codecov.io/) integration?
It would be nice to know the coverage changes for each PR.

### PR DESCRIPTION
**Pull request by SimenB**
Let's see what happens. I can delete some tests as a check for that behavior.

Closes #69

### CODE REVIEW

**Comment by SimenB** [comment]
Hmm, not sure how to get it into the status checks

**Comment by G-Rath** [comment]
What you remove some tests so that the coverage changes?

**Comment by SimenB** [comment]
@G-Rath seems to work? 🙂

**Comment by G-Rath** [comment]
Nice! thats useful <3

**Comment by SimenB** [comment]
It's not updating the comment, so I assume disabling it worked

**Pull request merged**
