### PR TITLE
feat: create `prefer-expect-resolves` rule

### LINKED ISSUE #803: [new rule] prefer `await expect(...).resolves`
Pretty much the opposite to the now-deprecated `no-expect-resolves`: prefer doing `await expect(...).resolves` over `expect(await ...)` as it gives a better failure message.

With `resolves`, if the promise rejects it'll fail the assertion, giving you an error on the lines of `expected promise to resolve but it rejected with ...`.
`expect(await ...)` however means that the rejection will be thrown "outside" of the `expect`, giving you a more generic "test thrown an unexpected error" message.

This also affected the behaviour of `expect.hasAssertions` & co, as with `resolves` you'll be hitting an assertion which fails, which is considered a "pass` in the eyes of `hasAssertions`.

I think `prefer-expect-resolves` could be a good name for this new rule.

### PR DESCRIPTION
**Pull request by G-Rath**
Resolves #803

I'd love to have a fixer, but `jest` kept giving me this:

```
(node:5300) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Node'
    |     property 'callee' -> object with constructor 'Node'
    --- property 'parent' closes the circle
    at stringify (<anonymous>)
    at writeChannelMessage (internal/child_process/serialization.js:117:20)
    at process.target._send (internal/child_process.js:805:17)
    at process.target.send (internal/child_process.js:703:19)
    at reportSuccess (/c/Users/G-Rath/workspace/projects-oss/eslint-plugin-jest/node_modules/jest-worker/build/workers/processChild.js:67:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

so will leave it as-is for now.

### CODE REVIEW

**Comment by SimenB** [comment]
@G-Rath as a workaround to that bug, you can try to run in band (`-i`)

**Comment by G-Rath** [comment]
@SimenB created a fixer 🎉

**Comment by SimenB** [comment]
@G-Rath can you rebase? 🙂

**Comment by fauxbytes** [comment]
Seems [this test](https://github.com/jest-community/eslint-plugin-jest/blob/2339fd0ebdfb73085b6e849e550108ab9c3a13e8/docs/rules/prefer-expect-resolves.md?plain=1#L61) is flawed. 
`s/rejects/reject/`
Plus, it fails?

**Comment by G-Rath** [comment]
@fauxbytes thanks, I've opened https://github.com/jest-community/eslint-plugin-jest/pull/1253 fixing this.

**Pull request merged**
