### PR TITLE
ci(lint): pass `configFile` to `commitlint` action

### PR DESCRIPTION
**Pull request by G-Rath**
@SimenB Turns out that the default is to look for `commitlint.config.js`, and to pass if it's not found 😬

### CODE REVIEW

**Comment by G-Rath** [comment]
I also bumped `actions/checkout` to `v2`, as it's meant to be faster since it only checkouts the first commit 🤷‍♂

**Comment by SimenB** [comment]
Weird it doesn't error out. Does it work? Mind pushing a non-conventional commit to verify?

**Comment by G-Rath** [comment]
I've been trying it on my companies [ESLint config repo](https://github.com/squareweave/eslint-config-ackama), which is how I found it out.

But yeah I'll push a commit up and we can see what happens

**Comment by G-Rath** [comment]
@SimenB there you go - it passes after I remove the config property 🤷‍♂

**Pull request merged**
