### PR TITLE
feat: remove deprecated rules

### PR DESCRIPTION
**Pull request by G-Rath**
BREAKING CHANGE

### CODE REVIEW

**Review by SimenB — APPROVED** [review]
Separate commit per rule so generated release log list each removed rule explicitly?

**Comment by G-Rath** [comment]
I was just going to do a `BREAKING CHANGE` per rule in the commit body (I confirmed the changelog generator is fine with this for a similar situation last night, via [this commit](https://github.com/ackama/eslint-config-ackama/pull/49/commits/1df125d8c88cec4f42f07c0b4351fd637cdbdf2f)), but can do multiple commits if you'd prefer :)

**Comment by SimenB** [comment]
If the changelog has multiple entries I'm happy 👍

**Comment by G-Rath** [comment]
@SimenB let's not forget this time 😅

**Comment by SimenB** [comment]
Let's not 😀

**Pull request merged**
