### PR TITLE
chore(ci): make sure to only make new releases if tests pass

### PR DESCRIPTION
**Pull request by SimenB**
https://github.com/jest-community/eslint-plugin-jest/runs/1914618070?check_suite_focus=true made a release even though tests were failing. #689 obviously didn't work, so let's bloat up a single file instead

I also added a `prepare-yarn-cache` job which ensures all other jobs have an updated cache _before_ running

### CODE REVIEW

**Comment by SimenB** [comment]
Things happened in the correct order here - `prepare-cache` ran first, and only when that completed did all the tests runs spawn. The `docs` job also ran (it's supposed to only run on PRs, so will verify it does _not_ run on master)

**Comment by SimenB** [comment]
a failing test made no difference, it only said "skipped" still

**Comment by G-Rath** [comment]
Sorry, I didn't realize we'd switched up CI like that - that explains why it released.

**Comment by SimenB** [comment]
Switched up? We've been using GH actions since Oct 2019 to make releases. And if you meant changes in #689 you did comment on them 😛

**Comment by G-Rath** [comment]
I meant #689 - the only comment j made in that PR was just now :)

(Unless the mobile UI is bidding previous comments?)

Still, no harm no foul 🤷‍♂️

**Comment by SimenB** [comment]
Regardless, seems fixed now 
image

**Comment by SimenB** [comment]
I've also deprecated the broken release

image

https://www.npmjs.com/package/eslint-plugin-jest/v/24.1.4

**Comment by G-Rath** [comment]
Cheers - sorry again for the hassle 😓

**Comment by SimenB** [comment]
No worries, I'm the one who set up the broken automation 😀

**Comment by G-Rath** [comment]
Btw while I've got you, would you be good to turn on [automatic deleting of head branches](https://docs.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches)?

**Comment by SimenB** [comment]
Nice, didn't know GH had added that! I guess that happens automatically for me since I use refined GH.

Turned on both of these bad boys

image

**Pull request merged**
