### PR TITLE
feat: support ESLint 8.x

### LINKED ISSUE #881: Support ESLint 8.x
ESLint has [released](https://eslint.org/blog/2021/08/eslint-v8.0.0-beta.0-released) the first beta version of v8 🎉

It would be awesome to have official ESLint 8 support. 👊
I'm happy to help where I can of course 🙂

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
ESLint has released the first beta versions of v8 🎉
https://eslint.org/blog/2021/08/eslint-v8.0.0-beta.0-released
https://eslint.org/blog/2021/08/eslint-v8.0.0-beta.1-released

Dependencies should be compatible with ESLint 8 too before we can merge this one:

- [ ] [`@typescript-eslint/experimental-utils`](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/experimental-utils) (https://github.com/typescript-eslint/typescript-eslint/issues/3738)
  - [ ] https://github.com/typescript-eslint/typescript-eslint/pull/2933
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3737
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3767
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3768
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3800
  - [ ] Release

devDependency compatibility with ESLint 8:

- [ ] [`@typescript-eslint/eslint-plugin`](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin) (https://github.com/typescript-eslint/typescript-eslint/issues/3738)
  - [ ] https://github.com/typescript-eslint/typescript-eslint/pull/2933
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3737
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3767
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3768
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3800
  - [ ] Release
- [ ] [`@typescript-eslint/parser`](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser) (https://github.com/typescript-eslint/typescript-eslint/issues/3738)
  - [ ] https://github.com/typescript-eslint/typescript-eslint/pull/2933
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3737
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3767
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3768
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3800
  - [ ] Release
- [ ] [`eslint-plugin-eslint-comments`](https://github.com/mysticatea/eslint-plugin-eslint-comments) (https://github.com/mysticatea/eslint-plugin-eslint-comments/issues/62)
  - [ ] https://github.com/mysticatea/eslint-plugin-eslint-comments/pull/63
  - [ ] Release
- [ ] [`eslint-plugin-eslint-config`](https://github.com/g-rath/eslint-plugin-eslint-config) (https://github.com/G-Rath/eslint-plugin-eslint-config/issues/8)
  - [ ] PR
  - [ ] Release
- [ ] [`eslint-plugin-eslint-plugin`](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin) (https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/issues/175)
  - [ ] https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/119
  - [ ] https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/151
  - [ ] Release
- [ ] [`eslint-plugin-import`](https://github.com/import-js/eslint-plugin-import) (https://github.com/import-js/eslint-plugin-import/issues/2211)
  - [ ] PR
  - [ ] Release
- [ ] [`eslint-plugin-node`](https://github.com/mysticatea/eslint-plugin-node) (https://github.com/mysticatea/eslint-plugin-node/issues/294)
  - [ ] https://github.com/mysticatea/eslint-plugin-node/pull/224
  - [ ] https://github.com/mysticatea/eslint-plugin-node/pull/295
  - [ ] Release
- [ ] [`eslint-plugin-prettier`](https://github.com/prettier/eslint-plugin-prettier) (https://github.com/prettier/eslint-plugin-prettier/issues/427)
  - [ ] https://github.com/prettier/eslint-plugin-prettier/pull/428
  - [ ] Release

---

BREAKING CHANGE: Requires Node@^12.22.0 || ^14.17.0 || >=16.0.0
BREAKING CHANGE: Requires ESLint@^6.x

Closes #881

### CODE REVIEW

**Comment by G-Rath** [comment]
Thanks but I don't know when we'll be able to land this since we tend to match supported node versions with Jest, which still supports v10 and I'd like to avoid adding more long-living PRs to our already decent list.

**Comment by SimenB** [comment]
I'm fine making a breaking change dropping node 10 (and eslint 5 if needed)

**Comment by MichaelDeBoey** [comment]
Since we have `@typescript-eslint/experimental-utils` as a dependency and it will drop support for Node v10 & ESLint v5, we don't really have a choice other than making these breaking changes.

I'm happy to re-open the PR.

**Comment by SimenB** [comment]
@MichaelDeBoey let's do it 🙂

**Comment by MichaelDeBoey** [comment]
@SimenB Since `@typescript-eslint/eslint-plugin` is a `peerDependency`, this will be breaking whenever we update

> BREAKING CHANGE: Requires Node@^12.22.0 || ^14.17.0 || >=16.0.0
> BREAKING CHANGE: Requires ESLint@^6.0.0 || ^7.0.0 || ^8.0.0-0
> BREAKING CHANGE: Requires @typescript-eslint/eslint-plugin@^5.0.0-0

**Comment by SimenB** [comment]
Not if we support both v4 and v5, right?

**Comment by MichaelDeBoey** [comment]
Running it with v5 will break peerDependency of `@typescript-eslint/experimental-utils` (which is in our `dependencies` and is still v4 for now).
Updating our `@typescript-eslint/experimental-utils` version to v5, will break our `peerDependency` then.

> I see the range is already `>=4`,

That should actually be `^4.0.0` for the same reason mention just above the quote

**Comment by SimenB** [comment]
Why would it break? `@typescript-eslint/eslint-plugin` pulls in its own version of the utils, I don't think this plugin cares what version it is.

**Comment by MichaelDeBoey** [comment]
@SimenB `@typescript-eslint/eslint-plugin` has `@typescript-eslint/parser` as `peerDependency` though.

https://github.com/typescript-eslint/typescript-eslint/blob/4a88de2c621ae645c070d995768006df8cb7e4df/packages/eslint-plugin/package.json#L64-L67

**Comment by SimenB** [comment]
Right, but that only affects users of the plugin, not us (I _think_) as we don't pull in the plugin, the user does

**Comment by MichaelDeBoey** [comment]
It technically affects our users too since it's our `peerDependency`, no? 🤔

**Comment by SimenB** [comment]
For us it's an optional one, we don't care which one the user pulls in. Us supporting two versions with different peer deps of their own doesn't matter, the user just pulls in the correct versions they use

**Comment by SimenB** [comment]
Regardless, we can start by dropping node v10 and eslint v5 on a `next` branch, then dig more into whether or not adding eslint v8 and ts-eslint v5 to our matrix messes anything up

**Comment by SimenB** [comment]
`next` now exists without node 10 or 15 and without eslint 5: https://github.com/jest-community/eslint-plugin-jest/tree/next

**Pull request closed without merging**
