### PR TITLE
chore: refresh lockfile

### PR DESCRIPTION
**Pull request by SimenB**
image

None of these matter, but annoying warning. hopefully this is enough to shut it up

### CODE REVIEW

**Comment by SimenB** [comment]
> Do you have any opinions on updating `package.json` w/ the latest versions?

no opinion beyond it creating a more noisy diff. so no opinion 😅

**Comment by G-Rath** [comment]
> no opinion beyond it creating a more noisy diff

Fair enough. Speaking of dependencies, do you have any roadmap on dropping `node@6`, or is it just "when jest does"?

**Comment by SimenB** [comment]
jest has dropped it on master, but I don't think we depend on that over here. I'm down with making a release whenever, just need to go over and decide on new recommended rules

**Comment by SimenB** [comment]
>Let me know when/how you'd like to do that (and if you'd like my input).

now is fine with me 👍 wanna open up a PR for discussion?

**Comment by G-Rath** [comment]
> now is fine with me

It's 11:40pm on a Saturday of a 3 day weekend here in New Zealand, so I've nothing stopping me from sleeping in tomorrow - lets do it!

> wanna open up a PR for discussion

Sure thing - I'll make one removing `node@6` where I can find, and go from there :)

**Pull request merged**
