### PR TITLE
fix: move @typescript-eslint/experimental-utils to dependencies

### PR DESCRIPTION
**Pull request by SimenB**
From mobile, seems correct?

### CODE REVIEW

**Comment by evocateur** [comment]
This completely breaks any consumer that doesn't have `typescript` installed.
```
> eslint --cache --cache-location ./node_modules/.cache/eslint/ *.js packages

Error: Cannot read config file: $PWD/node_modules/eslint-plugin-zillow/lib/eslint-plugin-zillow.js
Error: Cannot find module 'typescript'
Referenced from: $PWD/.eslintrc.yaml
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> ($PWD/node_modules/@typescript-eslint/typescript-estree/dist/parser.js:17:25)
```

It's unclear to me why an eslint plugin needs experimental typescript plugins in its dependencies.

**Comment by eaviles** [comment]
I'm still getting this error. See below:

```
$ jq '.version' node_modules/eslint-plugin-jest/package.json
"22.6.2"
avilesle at ROSELCDV0085289 in kinesis (release/1.0.2)
$ npm run eslint

> lifion-kinesis@1.0.1 eslint /Users/avilesle/Documents/Stash/OHCM/ditc/kinesis
> eslint . --ext .js,.json

Error: Cannot read config file: /Users/avilesle/Documents/Stash/OHCM/ditc/kinesis/node_modules/eslint-plugin-jest/lib/index.js
Error: Cannot find module 'typescript'
Referenced from: /Users/avilesle/Documents/Stash/OHCM/ditc/kinesis/node_modules/eslint-config-lifion/lib/index.js
Referenced from: /Users/avilesle/Documents/Stash/OHCM/ditc/kinesis/package.json
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/avilesle/Documents/Stash/OHCM/ditc/kinesis/node_modules/@typescript-eslint/typescript-estree/dist/parser.js:17:25)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! lifion-kinesis@1.0.1 eslint: `eslint . --ext .js,.json`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the lifion-kinesis@1.0.1 eslint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/avilesle/.npm/_logs/2019-05-22T16_38_10_085Z-debug.log
avilesle at ROSELCDV0085289 in kinesis (release/1.0.2)
```
```

**Comment by ranyitz** [comment]
@evocateur I think it's being used for some of the rules, for example [here](https://github.com/jest-community/eslint-plugin-jest/blob/83ff19810b73ff527d2d87b4c3f0f0fb36bd0fdb/src/rules/no-jest-import.ts#L1) which means that if it won't be in `eslint-plugin-jest`'s dependencies it will break the consumer.

`experimental-utils` has a peer dependency on [TypeScript](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/experimental-utils/package.json#L44) though, which I think was not taken into consideration as a breaking change when starting [adding support for typescript](https://github.com/jest-community/eslint-plugin-jest/issues/256).

@SimenB one optional solution is to say typescript is a `peerDependency` of `eslint-plugin-jest` but as this is a breaking change, I would consider adding it in a major version.

This is just an observation so I may be wrong here :sweat_smile: Let me know what you think.

**Comment by shazron** [comment]
Even after installing `typescript` as a peer dep, there is this error: #268

**Comment by SimenB** [comment]
Yeah, this is an unintended regression after rewriting 2 rules to TS - it was supposed to be an implementation detail! I'll revert and figure out a path forward once I'm at a computer.

So sorry about the mess! 🙏

**Comment by hbroer** [comment]
All fine. Shit happens :) I installed greenkeeper yesterday and this was a nice test of its integration :D He went so mad ;)

**Pull request merged**
