### PR TITLE
WIP: ts-migration/valid-expect

### PR DESCRIPTION
**Pull request by yatki**

### CODE REVIEW

**Comment by yatki** [comment]
@G-Rath I saw you did quite a lot work on migrating rules. Please take a look to this PR to avoid duplicating anything. I hope this helps :) Feel free to give feedback if you have better solutions.

Cheers,

**Comment by SimenB** [comment]
Woo! 🎉 

I'll be merging the TS migration shortly btw, including some heavy rebase work (I can do it for you if you want). So you can change this PR to point to master

**Comment by yatki** [comment]
@SimenB Thank you very much. I'll continue to work on it as soon as I have time this week (shouldn't be longer than 2-3 days).

**Comment by G-Rath** [comment]
This is awesome thanks!

I have already started a bit on this rule, but was also putting it off to do last as it uses most of the matchers. Instead I was aiming to convert some of the other guards first via rules that use less of them.

You've got a good base there that'll only get better - I can already see a few changes that will be required, and you shouldn't use *any* casts by the end of the conversation.

I'm currently in Melbourne until Wednesday for work, so I'll be working on the conversation on and off until the weekend, where I hope to go full force to get it finished by Monday :) 

tbh, part of me is wanting to put a hold on the conversation for a few days, just to see if #317 has caused any problems (which I think it might have w/ #334 😬)

Let me know if you'd like me to do any work on this branch at all, or have any questions :)

**Pull request closed without merging**
