### PR TITLE
Deprecate rules

### PR DESCRIPTION
**Pull request by G-Rath**
Per discussion in #575

### CODE REVIEW

**Comment by G-Rath** [comment]
Can I get a sanity check on the layout for squashing and merging?

Ideally we'd like a changelog entry for each deprecation, but I'm not sure if squashing this will give that - Semantic Pull Request is recommending a merge or rebase instead of a squash.

**Comment by SimenB** [comment]
Yeah, rebase merge is the way to go 👍

**Comment by SimenB** [comment]
might have been considered breaking, dunno... I have no idea how eslint handles deprecated rules. If it doesn't warn at all I guess it's fine, but then what's the point?

Meh 🤷

**Comment by G-Rath** [comment]
No it's not breaking - I can't remember the exact way it handles them, but I know it's at least not breaking enough for eslint & typescript-eslint to deprecate rules in minors :)

**Pull request merged**
