### PR TITLE
feat: remove `no-if` rule

### PR DESCRIPTION
**Pull request by G-Rath**
BREAKING CHANGE

### CODE REVIEW

**Comment by SimenB** [comment]
(not against it, but why? missing motivation/issue I think 😅 )

**Comment by G-Rath** [comment]
Do you mean for the changelog or that you've forgotten the history? (I don't blame you if so😅)

We replaced it with `no-conditional-in-test` which does the same but with more conditions, but we kept forgetting to actually remove this rule in our follow-up majors...

#1049 & #1027

**Comment by SimenB** [comment]
haha, both! 😅 The `BREAKING CHANGE` part of the commit message should include motivation/migration path.

**Comment by G-Rath** [comment]
🤦 it's been so long I forgot that

**Review by SimenB — APPROVED** [review]

**Pull request merged**
