### PR TITLE
ci: run tests against `eslint@7`

### LINKED ISSUE #568: Support ESLint 7.x
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉

It would be awesome to have official ESLint 7 support. 👊
I'm happy to help where I can of course 🙂

### PR DESCRIPTION
**Pull request by G-Rath**
Closes #568 
Closes #569

### CODE REVIEW

**Comment by SimenB** [comment]
https://github.com/jest-community/eslint-plugin-jest/blob/5e79476d5e943dde81ccb686647b0a3e408258a6/package.json#L59

?

**Comment by G-Rath** [comment]
I was holding off updating the actual dependence until our other dependencies were updated, but happy to bump it if you don't mind the peer dependency warnings 🙂

**Comment by SimenB** [comment]
Aha! I probably won't see the dependency warnings anyways 😀 But good call on holding off, those are annoying 👍

**Comment by SimenB** [comment]
@G-Rath a thought, should we drop eslint 5 and increase minimum supported version to 6.7 and use the Suggestions API for out more dangerous autofixes? Such as `toStrictEqual` - that does change the semantic meaning, but especially `no-test-callback` as we've discussed previously

**Comment by G-Rath** [comment]
I'm always keen to drop old versions - I was actually opening an issue to discuss these things halfway during the day but then did some house chores, applied a Windows update, etc

Lucky the powers of Chrome & Github have the issue body saved - I'll hit post and we can begin discussions :D

**Pull request merged**
