### PR TITLE
feat(rules): add no-test-prefixes rule

### PR DESCRIPTION
**Pull request by ranyitz**
This PR adds the `no-test-prefixes` rule that discussed in #63 

**TL;DR**
Do not use `f` and `x` prefixes for focused/skipped tests.

### CODE REVIEW

**Comment by SimenB** [comment]
This is great! I'm not sure about the name, though... @thymikee ideas for a better name?

**Comment by thymikee** [comment]
Dang, this is hard to tackle. `prefer-no-aliased-test-methods` is maybe more generic?

**Comment by SimenB** [comment]
`prefer-no-modifier-prefix`?

**Comment by thymikee** [comment]
`prefer-no-test-prefixes`?

**Comment by ranyitz** [comment]
`no-test-prefixes`?

**Comment by SimenB** [comment]
`no-test-prefixes` 👍

**Comment by ranyitz** [comment]
@SimenB @thymikee Ok great, I will change it later on today :blush:

**Comment by ranyitz** [comment]
I've updated the name and the PR is ready for a review/merge 🙂

**Pull request merged**
